import {
  BadgeCheck,
  Banknote,
  BarChart3,
  Building2,
  CalendarClock,
  CircleDollarSign,
  ClipboardList,
  FileText,
  Flag,
  Gauge,
  Inbox,
  LayoutDashboard,
  Map,
  Package,
  Receipt,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Store,
  Users,
  UserRound,
  Wallet,
  XCircle,
  type LucideIcon,
} from "lucide-react";

/**
 * Nav icons are referenced by name so nav configs can be built in server
 * components and passed across the RSC boundary as plain data.
 */
export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  leads: ClipboardList,
  lostCancelled: XCircle,
  upcoming: CalendarClock,
  crm: UserRound,
  itineraries: Map,
  marketplace: Store,
  payments: Wallet,
  invoices: Receipt,
  reports: BarChart3,
  users: Users,
  settings: Settings,
  billing: CircleDollarSign,
  profile: BadgeCheck,
  verify: ShieldCheck,
  accounts: Building2,
  disputes: Flag,
  revenue: Banknote,
  listings: ShoppingBag,
  overview: Gauge,
  requests: Inbox,
  packages: Package,
  legal: FileText,
};
